export const quotes = [
  "People will reach the stars in the future, If they live meaningfully in the present.",
  "What is the meaning of life? Live a good life, and its fruits will be its meaning.",
  "Homo sapiens is a child of the most ancient humans, resulting from their self-survival. Therefore, a tribute to them is love for humankind.",
  "How prideful sounds the phrase: \"It is not nature that created a human, but he himself!”",
  "To understand and live life in its fullness is a person's dignity and pride.",
  "Modern humankind can solve the problems it faces only by understanding the unique significance of its existence.",
  "The basic question of philosophy can be formulated as follows: \"What are the criteria for a right life?\"",
  "Truly beauty is the highest value, on par with the good and the truth.",
  "If the contingency is primordial, the mystery of evil is understandable.",
  "A person's creed – my life must be filled with a worthy meaning, and this is above all.",
  "Without love for life, neither human obligations, nor their fulfillment would be possible. Only with love can duty be a free choice and an exciting decent pursuit. ",
  "The purpose of life is to live meaningfully, productively, and emotionally–saturate. In other words, to live fully.",
  "The main source of well-being – is a conscious and persistent wish to live fully.",
  "Humanity will break out of any web, it only has to comprehend the value of love and truth.",
  "The worldview of a modern person should be formed based on scientific knowledge and respect for positive rational traditions.",
  "If for the ancient, newborn Homo sapiens, the mind was a survival tool, and for the modern human, it is the obligation to live responsibly and meaningfully.",
  "A person's spiritual development begins with his conscious desire for knowledge of important worldview issues, goodness, and humanity, and understanding and perception of beauty.",
  "For each person, it is necessary to find a reasonable answer to the most important questions: \"What is life? What are the criteria for a right life?\".",
  "Life is being ready for trials and being able to overcome them.",
  "The more scientific worldview a person has, the more logical his thinking is.",
  "Instilling love for life is cultivating an ability to consciously see the valuable and the beautiful, and fill one's feeling and thoughts with them. ",
  "An incomprehensible metaphysics is a bizarre physics that, like other marvels, science one day will reveal.",
  "The evolution factors and mass extinctions in the history of life on Earth point to the absence of a definite aim for the emergence of life and the process of evolution.",
  "A strong personality will not step over the ideals that shaped it. His principles can not allow it.",
  "Reverence for life is an inexhaustible energy source for a meaningful and happy life.",
  "Life is explainable if the Universe is aimless.",
  "The goal is high when love is vast.",
  "The criteria for happiness and the meaning of life of a modern person must correspond to the achievements that are obtainable in the process of his genuine self-realization.",
  "Realizing life is remarkable makes a person more open to accepting scientific knowledge about its origin.",
  "Who, or rather what, are Homo sapiens? The more accurate the knowledge about him, the clearer path for the further development of human society.",
  "It is the fruits of serving true ideals that fill our lives with meaning and maintain a lively connection between generations.",
  "Society is ultimately driven by its moral force.",
  "Self-awareness of infinite consciousness is impossible.",
  "Even the Universe is eternal as long as our humanity is impeccable.",
  "A mature person has a unique property — a conscious responsibility to realize himself at its fullness.",
  "Mind is more inquisitive – Universe is more random.",
  "The greatness of the human race is manifested in its created sustainable, humane civilization for the happiness of every person.",
  "The effectiveness of popularizing evolution knowledge depends on its fascination, as the entrenched stereotypes of people about the sacred status of a human being in the Universe prevents the perception of information that equates him with living nature and devalues this status.",
  "Beautiful human feelings and emotions were formed in a long evolutionary process, primarily due to love, work, cooperation, and the exploits and hopes of the most ancient and ancient people. If life is joy, love to a human is virtue and pride!",
  "If there is possibly an eternal, endless space filled with moving matter, then the birth of intelligent beings becomes impossible.",
  "Homo sapiens, although not a saint but is good enough. We have what we have. The main thing is that there is a great chance to upbringing and create a new kind of human – Homo humanus, the Human humane.",
  "Self-actualization leads to countless of achievements: humanity, creativity, the satisfaction of needs, caring for loved ones, giving meaning to life, fulfillment of duty, a decent life, pride, happiness, and as well as the opportunity to leave a good memory of yourself.",
  "Happiness is not only the satisfaction of own meaningful and productive life but also with the development of society.",
  "Absolute intelligence is possible if its quiescence is equally absolute.",
  "The happiness and meaning of an educated person's life are inseparable from humanity's fate – no tranquility without confidence in a reliable future.",
  "Love and devotion are beyond the power of artificial intelligence — it always loses to the reasonable human.",
  "The very fact of our existence is a miracle that causes surprise even the greatest minds.",
  "The key value of spirituality is its focus on making life more humane, creation of a reliable future for everyone, and Human's ascension to a more sophisticated state.",
  "The more are striving to live fully, the safer the world.",
  "The world, at its root, is random but also quite pleasant.",
  "The assumption that the human mind has limitations in understanding the ultimate questions of the universe due to the specifics of its evolutionary process is incorrect. Yes, the mind could form better, but it has led humans to the current level of development, while creating incredible sciences of cognition with a vast horizon for further improvement. Therefore, we are obliged to follow its rational conclusions.",
  "People, by the will of chance, have an amazing opportunity to spread the seeds of life throughout the universe. This is a sensibly proud responsibility, and any thought that ignores this is cowardly and indifferent.",
  "The Achilles heel of modern humanity is its spiritual weakness, which threatens to devalue the content and meaning of universal human values on the path to global solidarity - moral, cultural, and political, which ultimately can lead to a global catastrophe.",
  "An individual's aspirations are productive when society's beliefs are rational.",
  "What drives our love for life and our desire for it to be eternal? Perhaps it is the awareness of the value of human life and its culture, and experiencing feelings and emotions that bring joy. And for the sake of love and dreams, it is important to live fully and with dignity.",
  "The emergence of the genus Homo was due to a favorable combination of circumstances, but its further evolution towards full intelligence required its active participation.",
  "The loss of control over a strong artificial intelligence, with possible catastrophic consequences, can only occur due to human fault, as they always know that allowing certain algorithms can lead to such an outcome. Taking such a step is a lack of humanism.",
  "It would be wise to look at modern humanity through the eyes of the Universe, imagining it as a daring youth, growing in complex conditions and simultaneously capable of greatness. Such a vision undoubtedly strengthens optimism and love for humanity.",
  "One should not be offended by the Universe, for it is aimless. However, expressing gratitude is important.",
  "Happiness — noticing within oneself, in one's surroundings, and in life as a whole, the fullness of the manifestation of human virtues.",
];